name: Parasol CI
run-name: "CI / ${{ github.event_name == 'workflow_dispatch' && inputs.evm_tag || github.event_name == 'pull_request' && github.event.pull_request.title || 'build' }} / ${{ github.event_name }}"

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
  push:
    branches:
      - parasol-dev
      - '[vt][0-9].[0-9]+.[0-9x]+*'
  workflow_dispatch:

env:
  IMAGE_NAME: neonlabsorg/parasol-node

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: gha-runner-scale-set-large
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            tag="${GITHUB_HEAD_REF}"
          elif [[ "${GITHUB_REF}" == refs/heads/parasol-dev ]]; then
            tag="latest"
          else
            tag="${GITHUB_REF_NAME}"
          fi
          tag="${tag//\//-}"
          echo "image_tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.image_tag }}
          outputs: type=local,dest=./bin
          push: true
    outputs:
        image-tag: ${{ steps.vars.outputs.image_tag }}

  prepare-infrastructure:
    needs: build
    runs-on: gha-runner-scale-set
    timeout-minutes: 25
    if: always()
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout dynamic-ci-cd workflows
        uses: actions/checkout@v4
        with:
          repository: neonlabsorg/dynamic-ci-cd
          ref: main
          token: ${{ secrets.GHTOKEN }}
          path: ./dynamic-ci-cd/.github/workflows

      - name: Create instance
        uses: ./dynamic-ci-cd/.github/workflows/actions/create-instance
        id: create-instance
        with:
          project-repository: ${{ github.event.repository.name }}
          run-id: ${{ github.run_id }}
          cpu: 4
          memory: 8
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}

      - name: Install Docker on instance
        uses: ./dynamic-ci-cd/.github/workflows/actions/prepare-docker-instance
        id: prepare-docker-instance
        with:
          host: ${{ steps.create-instance.outputs.public-ip-v4 }}
          ssh-user: ${{ steps.create-instance.outputs.ssh-user }}
          ssh-key: ${{ steps.create-instance.outputs.ssh-key }}

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext
        shell: bash

      - name: Render docker-compose.yml with envsubst
        id: read_compose_file
        shell: bash
        run: |
          rendered=$(envsubst < ./ci/docker-compose.yml)
          echo "value<<EOF" >> "$GITHUB_OUTPUT"
          echo "$rendered" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          PARASOL_NODE_IMAGE: ${{ env.IMAGE_NAME }}:${{github.sha}}

      - name: Debug
        shell: bash
        run: echo "${{ steps.read_compose_file.outputs.value }}"

      - name: Run docker containers
        uses: ./dynamic-ci-cd/.github/workflows/actions/run-docker-containers
        id: run-docker-containerss
        with:
            docker_host: ${{ steps.create-instance.outputs.public-ip-v4 }}
            docker_ca_cert: ${{ steps.prepare-docker-instance.outputs.docker_ca_cert }}
            docker_cert: ${{ steps.prepare-docker-instance.outputs.docker_cert }}
            docker_key: ${{ steps.prepare-docker-instance.outputs.docker_key }}
            docker_containers_wait_for_ready_seconds: 30
            docker_compose: ${{ steps.read_compose_file.outputs.value }}
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_password: ${{ secrets.DOCKER_PASSWORD }}
    outputs:
      parasol_node_ip: ${{ steps.create-instance.outputs.public-ip-v4 }}

  run-tests:
    needs: prepare-infrastructure
    runs-on: gha-runner-scale-set-large
    env:
      PARASOL_NODE_IP: ${{ needs.prepare-infrastructure.outputs.parasol_node_ip }}
      TEST_IMAGE: neonlabsorg/parasol-tests:main
      CONTAINER_NAME: parasol-tests-${{ github.run_id }}
      SOLANA_URL: http://${{ needs.prepare-infrastructure.outputs.parasol_node_ip }}:8899
      WS_SOLANA_URL: ws://${{ needs.prepare-infrastructure.outputs.parasol_node_ip }}:8900
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker pull test image
        run: docker pull ${{ env.TEST_IMAGE }}
      - name: Deploy test programs
        run: |
          docker run --rm \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ env.TEST_IMAGE }} \
            /bin/bash -c "./solana_programs/deploy.sh ${{ env.SOLANA_URL }} ${{ env.WS_SOLANA_URL }}"
      - name: Run tests
        run: |
          docker run --rm \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ env.TEST_IMAGE }}  \
            /bin/bash -c "pytest --solana-url ${{ env.SOLANA_URL }} --metrics-url ${{ env.SOLANA_URL }}/metrics"

  destroy-terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    needs:
      - prepare-infrastructure
      - run-tests
    runs-on: ["gha-runner-scale-set"]
    if: always()
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - uses: actions/checkout@v4
      with:
        repository: 'neonlabsorg/dynamic-ci-cd'
        ref: 'main'
        token: ${{ secrets.GHTOKEN }}
        path: dynamic-ci-cd
    - name: Fetch docker logs
      uses: ./dynamic-ci-cd/actions/fetch-docker-container-logs
      with:
          docker_host: ${{ needs.prepare-infrastructure.outputs.proxy_ip }}
          docker_ca_cert: ${{ needs.prepare-infrastructure.outputs.docker_ca_cert }}
          docker_cert: ${{ needs.prepare-infrastructure.outputs.docker_cert }}
          docker_key: ${{ needs.prepare-infrastructure.outputs.docker_key }}
          container_names: "parasol-node"
    - name: Set output
      id: vars
      run: echo "bname=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Delete instance
      uses: ./dynamic-ci-cd/actions/delete-instance
      id: delete-instance
      with:
        project-repository: ${{ github.event.repository.name }}
        job-id: ${{ github.job }}
        run-id: ${{github.run_id}}
        hcloud-token: ${{ secrets.HCLOUD_TOKEN }}